[package]
name = "ant-system"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]
name = "ant_system"
crate-type = ["rlib", "staticlib"]

[features]


[dependencies]